name: codecov
on: [push, pull_request]

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Install checkout
        uses: actions/checkout@v4

      - name: Install checkout
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Run coverage
        run: |
          for MOD_FILE in $(find . -name 'go.mod' | grep -Ev '^\./go\.mod'); do
            pushd "$(dirname ${MOD_FILE})"
            # go test ${{ matrix.testflags }} -cpu 1,4 -timeout 2m ./...
            go test -coverprofile=coverage.out -coverpkg=./... ./...
            popd
          done

      - name: Run coverage with new pickfirst
        run: |
          export GRPC_EXPERIMENTAL_ENABLE_NEW_PICK_FIRST=true
          for MOD_FILE in $(find . -name 'go.mod' | grep -Ev '^\./go\.mod'); do
            pushd "$(dirname ${MOD_FILE})"
            go test -coverprofile=coverage_new_pickfirst.out -coverpkg=./... ./...
            popd
          done

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
