name: Dependency Changes

# Trigger on PRs.
on:
  pull_request:

permissions:
  contents: read

jobs:
  # Compare dependencies before and after this PR.
  dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: "**/*go.sum"

      # Run the commands to generate dependencies before and after and compare.
      - name: Compare dependencies
        run: |
          set -eux
          BASE_REF="${GITHUB_BASE_REF:-master}"
          # Suffixes passed to mktemp must not contain "/".
          BEFORE_SUFFIX="${BASE_REF//\//_}"
          AFTER_SUFFIX="${GITHUB_HEAD_REF//\//_}"

          BEFORE="$(mktemp -d --suffix="-${BEFORE_SUFFIX}")"
          AFTER="$(mktemp -d --suffix="-${AFTER_SUFFIX}")"

          scripts/gen-deps.sh "${AFTER}"
          # GITHUB_BASE_REF is set when the job is triggered by a PR.
          git checkout origin/"${BASE_REF}"
          scripts/gen-deps.sh "${BEFORE}"

          echo "Comparing dependencies..."
          # Run grep in a sub-shell since bash does not support ! in the middle of a pipe
          diff -u0 -r "${BEFORE}" "${AFTER}" | bash -c '! grep -v "@@"'
          echo "No changes detected."
